export const ADMIN_USERINFOR_REQUEST = 'ADMIN_USERINFOR_REQUEST';
export const ADMIN_USERINFOR_SUCCESS = 'ADMIN_USERINFOR_SUCCESS';
export const ADMIN_USERINFOR_FAILURE = 'ADMIN_USERINFOR_FAILURE';

// ADD USER ACCOUNT
export const ADD_USERINFOR_REQUEST = 'ADD_USERINFOR_REQUEST';
export const ADD_USERINFOR_SUCCESS = 'ADD_USERINFOR_SUCCESS';
export const ADD_USERINFOR_FAILURE = 'ADD_USERINFOR_FAILURE';

// UPDATE USER ACCOUNT
export const UPDATE_USERINFOR_REQUEST = 'UPDATE_USERINFOR_REQUEST';
export const UPDATE_USERINFOR_SUCCESS = 'UPDATE_USERINFOR_SUCCESS';
export const UPDATE_USERINFOR_FAILURE = 'UPDATE_USERINFOR_FAILURE';


// DELETE USER ACCOUNT
export const DELETE_USERINFOR_REQUEST = 'DELETE_USERINFOR_REQUEST';
export const DELETE_USERINFOR_SUCCESS = 'DELETE_USERINFOR_SUCCESS';
export const DELETE_USERINFOR_FAILURE = 'DELETE_USERINFOR_FAILURE';