export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const PAYMENT_FAILURE = 'PAYMENT_FAILURE';

export const LOAD_PAYMENT_REQUEST = 'LOAD_PAYMENT_REQUEST';
export const LOAD_PAYMENT_SUCCESS = 'LOAD_PAYMENT_SUCCESS';
export const LOAD_PAYMENT_FAILURE = 'LOAD_PAYMENT_FAILURE';