export const WALLET_REQUEST = 'WALLET_REQUEST';
export const WALLET_SUCCESS = 'WALLET_SUCCESS';
export const WALLET_FAILURE = 'WALLET_FAILURE';


export const ADD_MONEY_REQUEST = 'ADD_MONEY_REQUEST';
export const ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS';
export const ADD_MONEY_FAILURE = 'ADD_MONEY_FAILURE';